# Generated by Django 4.2.19 on 2025-02-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="LinkedProject", to="project.project"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="LinkedSkill", to="core.skill"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="Project", to="project.project"
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ProjectLinkType", to="core.linktype"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="projectskill",
            constraint=models.UniqueConstraint(fields=("project", "skill"), name="unique_project_skill"),
        ),
    ]
