# Generated by Django 4.2.19 on 2025-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=25)),
                ("logo_uri", models.CharField(max_length=255)),
            ],
        ),
    ]
