# Generated by Django 4.2.19 on 2025-02-12 05:34

from django.db import migrations


def add_default_countries(apps, schema_editor):
    Country = apps.get_model("core", "Country")

    default_countries = [
        {"name": "United States", "code": "US"},
        {"name": "India", "code": "IN"},
        {"name": "Germany", "code": "DE"},
        {"name": "France", "code": "FR"},
        {"name": "United Kingdom", "code": "GB"},
    ]

    for country in default_countries:
        Country.objects.get_or_create(name=country["name"], code=country["code"])


def remove_default_countries(apps, schema_editor):
    Country = apps.get_model("core", "Country")
    Country.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_default_countries, remove_default_countries)]
