repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3  # Change if needed

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8
        args: ["--config=server/.flake8"]
