# Generated by Django 4.2.19 on 2025-02-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo_uri", models.CharField(max_length=255)),
                (
                    "tier",
                    models.CharField(
                        choices=[("tier_1", "Tier 1"), ("tier_2", "Tier 2"), ("tier_3", "Tier 3")], max_length=30
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="Company", to="company.company"
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="LinkTypeCompany", to="core.linktype"
                    ),
                ),
            ],
        ),
    ]
