# Generated by Django 4.2.19 on 2025-02-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_skill"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="LinkedCompany", to="company.company"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="LinkedSkillCompany", to="core.skill"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="companyskill",
            constraint=models.UniqueConstraint(fields=("company", "skill"), name="unique_company_skill"),
        ),
    ]
