# Generated by Django 4.2.19 on 2025-02-11 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalInstitute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo_uri", models.CharField(max_length=255)),
                (
                    "selection_difficulty",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="EducationInstituteCountry",
                        to="core.country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="EducationInstituteState",
                        to="core.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationalInstituteSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "educational_institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LinkedEducationalInstitute",
                        to="educational_institute.educationalinstitute",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LinkedSkillEducationalInstitute",
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationalInstituteLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=255)),
                (
                    "educational_institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="EducationalInstitute",
                        to="educational_institute.educationalinstitute",
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="LinkType", to="core.linktype"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="educationalinstituteskill",
            constraint=models.UniqueConstraint(
                fields=("educational_institute", "skill"), name="unique_education_institute_skills"
            ),
        ),
    ]
