# Generated by Django 4.2.19 on 2025-02-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20250212_1104"),
        ("educational_institute", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationalinstitutelink",
            name="educational_institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educational_institute_links",
                to="educational_institute.educationalinstitute",
            ),
        ),
        migrations.AlterField(
            model_name="educationalinstitutelink",
            name="link_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educational_institute_link_type",
                to="core.linktype",
            ),
        ),
        migrations.DeleteModel(
            name="EducationalInstituteSkill",
        ),
    ]
