# Generated by Django 4.2.19 on 2025-02-11 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo_uri", models.CharField(max_length=255)),
                (
                    "completion_difficulty",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("certification_id", models.CharField(max_length=255, null=True)),
                ("certification_url", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CertificationSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LinkedCertification",
                        to="certification.certification",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LinkedSkillCertification",
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificationLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=255)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Certification",
                        to="certification.certification",
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CertificationLinkType",
                        to="core.linktype",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="certificationskill",
            constraint=models.UniqueConstraint(fields=("certification", "skill"), name="unique_certification_skill"),
        ),
    ]
