# Generated by Django 4.2.19 on 2025-02-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_skill"),
        ("certification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LinkedCertification",
                        to="certification.certification",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="LinkedSkillCertification",
                        to="core.skill",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="certificationskill",
            constraint=models.UniqueConstraint(fields=("certification", "skill"), name="unique_certification_skill"),
        ),
    ]
